name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm install

    - name: Check for package updates
      run: |
        npx ncu --doctor -u

    - name: Persist changes in package.json
      run: |
        git add package.json package-lock.json
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Update packages" || echo "No changes to commit"

    - name: Push changes of package.json
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: false

    - name: Lint and test the application
      run: |
        npm run lint
        npm test

    - name: Build the application
      run: |
        npm run build
